routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {

    return view('login');
});*/


Auth::routes();

	Route::get('password/reset', 'Auth\FrontendForgotPasswordController@showLinkRequestForm')->name('password.request');	
	Route::get('password/reset/{token}', 'Auth\FrontendResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'Auth\FrontendResetPasswordController@reset')->name('password.update');
	Route::get('password/confirm/{token}', 'EmailController@confirm')->name('password.confirm');
	Route::post('password/reset/change-password', 'EmailController@change_password')->name('password.change-password');
	Route::post('password/email', 'EmailController@reset_password')->name('password.email');

	// quên mật khẩu admin 
	Route::get('admin-password/reset', 'Auth\ForgotPasswordController@showLinkRequestFormAdmin')->name('admin-password.request');
	Route::post('admin-password/email', 'EmailController@reset_password_admin')->name('admin-password.email');

	Route::get('admin-password/reset/{token}', 'Auth\ResetPasswordController@showResetFormAdmin')->name('admin-password.reset');
	Route::post('admin-password/reset', 'Auth\ResetPasswordController@reset')->name('admin-password.update');

	Route::get('admin-password/confirm/{token}', 'EmailController@confirm_admin')->name('admin-password.confirm');
	Route::post('admin-password/reset/change-password', 'EmailController@change_password_admin')->name('admin-password.change-password');


Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	
	Route::get('product-category-parent/{alias}','HomeController@get_category_parent')->name('product-category-parent');
	Route::get('product-category/{alias}/{parent}','HomeController@product_category')->name('product-category');
	Route::get('product-detail/{alias}','HomeController@product_detail')->name('product-detail');

	Route::get('can-ho/{alias}','HomeController@getCan_ho')->name('can-ho');
	Route::get('can-ho-detail/{alias}','HomeController@temp_detail')->name('can-ho-detail');
	
	Route::get('gioi-thieu','HomeController@about')->name('gioi-thieu');

	// Route::get('project','HomeController@project_news')->name('project');
	// Route::get('project-detail/{alias}','HomeController@project_detail')->name('project-detail');

	Route::get('tin-tuc','HomeController@getNews')->name('news');
	Route::get('tin-tuc/{alias}','HomeController@news_detail')->name('news-detail');

	Route::get('danh-muc-tin-tuc/{id}/{alias}','HomeController@newsCategory')->name('news-category');

	Route::get('contact','HomeController@ContactCompany')->name('contact');
	Route::get('lien-he','HomeController@contactUs')->name('lien-he');
	Route::post('lien-he','HomeController@storeContact')->name('lien-he.store');

	Route::get('dangnhap','HomeController@getDangnhap')->name('dangnhap');
	Route::post('dangnhap','HomeController@postDangnhap');

	Route::get('register', 'HomeController@RegisterAccount');
	Route::get('registersucces', 'HomeController@Registersucces');
	
	Route::get('dangky','HomeController@getDangky')->name('dangky');
	Route::post('dangky','HomeController@postDangky');

	Route::get('dangxuat','HomeController@getDangxuat')->name('dangxuat');

	Route::get('tin-dang','HomeController@create')->name('quanlytk.create');
	Route::post('tin-dang','HomeController@store')->name('quanlytk.store');
	Route::get('tin-dang/{alias}','HomeController@edit')->name('quanlytd.edit');
	Route::post('tin-dang/{alias}','HomeController@update')->name('quanlytd.update');
	Route::get('tin-dang/{id}/delete','HomeController@destroyQuanlytd')->name('quanlytk.destroy');

	Route::get('dang-tin-can-ho','HomeController@CreateCanho')->name('quanlytk.CreateCanho');
	Route::post('dang-tin-can-ho','HomeController@StoreCanho')->name('quanlytk.StoreCanho');
	Route::get('sua-tin-can-ho/{alias}','HomeController@EditCanHo')->name('quanlycanho.EditCanHo');
	Route::post('sua-tin-can-ho/{alias}','HomeController@UpdateCanHo')->name('quanlycanho.UpdateCanHo');
	Route::get('tin-dang-can-ho/{id}/delete','HomeController@destroyCanho')->name('quanlytk.destroyCanho');


	Route::get('quan-ly-tai-khoan','HomeController@editQuanlytk')->name('quanlytk.edit');
	Route::post('quan-ly-tai-khoan','HomeController@updateQuanlytk')->name('quanlytk.update');
	
	Route::post('change-password','HomeController@updateChangePassword')->name('changepass.update');
	
	Route::post('dangnhap','HomeController@postDangnhap');

	Route::get('tim-kiem','HomeController@get_timkiem')->name('tim-kiem');
	Route::post('tim-kiem','HomeController@timkiem')->name('tim-kiem');
	
	Route::post('search-can-ho','HomeController@postSearch')->name('search-can-ho');

	Route::get('view-more-can-ho','HomeController@getViewCanho')->name('view-more-can-ho');
	Route::get('view-more-nha-dat','HomeController@getViewNhadat')->name('view-more-nha-dat');

});


Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
Route::post('sign-in','LoginController@postLogin');
Route::get('logout','LoginController@getLogout')->name('getLogout');


Route::namespace('Backend')->middleware('login')->prefix('admin')->group(function(){
	
	 Route::resource('/','HomeController');
	
	 Route::get('index','AdminController@index')->name('admin.index');
	 Route::get('add','AdminController@create')->name('admin.create');
	 Route::post('add','AdminController@store')->name('admin.store');
	 Route::get('edit/{id}','AdminController@edit')->name('admin.edit');
	 Route::post('edit/{id}','AdminController@update')->name('admin.update');
	 Route::get('delete/{id}','AdminController@destroy')->name('admin.destroy');

	 Route::get('change-password','AdminController@Getchangepass')->name('change-password');
	 Route::post('change-password','AdminController@Postchangepass');

	 Route::resource('dmtd','DMTDController');
	 Route::resource('dmtt','DMTTController');
	 Route::resource('danh-muc-can-ho','DMCanHoController');
	 Route::resource('can-ho','CanHoController');
	 // Route::resource('duan','DuAnController');
	 Route::resource('lienhe','LienHeController');
	 Route::resource('member','MemberController');
	 Route::resource('menu','MenuController');
	 Route::resource('slider','SliderController');
	 Route::resource('tindang','TinDangController');
	 Route::resource('tin-tuc','TinTucController');
	 Route::resource('video','VideoController');
	 Route::resource('gioithieu','IntroduceController');
	 Route::resource('logo','LogoController');
	 Route::resource('mangxahoi','SocialNetworkController');
	 Route::resource('googlemap','GoogleMapController');
	 Route::resource('contactus','ContactUsController');
	 Route::resource('footer','FooterController');
	 Route::resource('cauhinhkhac','ConfigurationController');
});

Route::get('clear-cache','LoginController@clear_cache');

resources/views/admin/modules/temp/index.blade.php
@extends('admin.master') 
@section('title','Danh Sách Căn Hộ') 
@section('content')
@include('admin.blocks.alert')
<div class="content">

    <!-- Page length options -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Danh sách căn hộ</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <a href="{{route('can-ho.create')}}">
                <button type="button" class="btn btn-primary">Thêm căn hộ</button>
            </a>
        </div>
        <form id="listForm" action="{{route('can-ho.destroy',['action' => 'delete'])}}" method="POST">
            @method('DELETE')
            @csrf
        <table class="table datatable-show-all">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                    </th>
                    <th>ID</th>
                    <th>Tiêu đề</th>
                    <th>Diện tích(m²)</th>
                    <th>Giá(VND)</th>
                    <th>Ưu tiên</th>
                    <th>Duyệt bài</th>
                    <th>Hoạt động</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($temp as $item)
                <tr>
                    <td>
                        <input type="checkbox" name="checked[]" value="{{$item->id}}">
                    </td>
                    <td>{{$item->id}}</td>
                    <td>{{ $item->title }}</td>
                    <td>{{ $item->dientich .'m²' }}</td>
                    <td>{{ number_format($item->priceCDT,0,",",".") }}</td>
                      <td>
                        <div class="form-check form-check-switchery">
                            <label class="form-check-label">
                                <input type="checkbox" data-id="{{ $item->id }}" name="hot" class="form-check-input-switchery" {{ $item->hot ? 'checked' : '' }} >
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="form-check form-check form-check-switchery form-check-switchery-sm">
                            <label class="form-check-label">
                                <input type="checkbox" data-id="{{ $item->id }}" name="status" class="form-input-switchery" {{ $item->status ? 'checked' : '' }}  >
                            </label>
                        </div>
                    </td>                  
                    <td>{{ date("d/m/Y",strtotime($item ->created_at))}}</td>
                    <td class="text-center">                       
                        <a href="{{ route('can-ho.edit',['can-ho' => $item->id]) }}" class="list-icons-item text-primary-600" title="Sửa tin căn hộ"><i class="icon-pencil7"></i></a> &nbsp;
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
            <button type="submit" class="btn btn-danger" onclick="return acceptDelete()" style="margin-left: 10px">{{trans('template.Delete')}}</button><br/><br>              
        </form>
    </div>
    <!-- /page length options -->
</div>
<script type="text/javascript">
    function checkallClick(o) {
            var form = document.listForm;
            for (var i = 0; i < form.elements.length; i++) {
                if (form.elements[i].type == "checkbox" && form.elements[i].name!="checkAll") {
                    form.elements[i].checked = document.listForm.checkAll.checked;
                }
            }
        }


$(document).ready(function () {
    $('.form-check-input-switchery').on('click',function () {
        var Id = $(this).data('id');
        var hot = this.checked;
        $.ajax({
            type: "POST",
            url: "../api/can-ho",
            data: {
                id: Id,
                hot: hot
            },
            success: function (result) {  
                    console.log(result.msg);
            },
            error: function () {
                console.log('Lỗi rồi,debug đi nhé.');
            }
        })
    });
});
$(document).ready(function () {
    $('.form-input-switchery').on('click',function () {
        var Id = $(this).data('id');
        var status = this.checked;
        $.ajax({
            type: "POST",
            url: "../api/duyet-bai-can-ho",
            data: {
                id: Id,
                status: status
            },
            success: function (result) {  
                    console.log(result.msg);
            },
            error: function () {
                console.log('Bị hack rồi nha bạn :D');
            }
        })
    });
});

</script>
@endsection